### ISSUE TITLE
Bug: The linter Updates the modified date for unmodified files sync'd by a foreign user

### ISSUE THREAD

**Issue by Bluemandan** [platers/obsidian-linter#1414]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When using the Linter plugin to insert YAML timestamps, it will change the modified date for a file that has been sync'd to the vault from a user with a different file system time. Even if the file was already linted before syncing, if a new user opens it up, it will lint again. I believe this is because of me and the other user having different time zones, though all our settings are in sync, I have Override Local set to en-us, I also enabled "Keep track of the date the file was last edited in the YAML front matter. Gets dates from file metadata".

## How to Reproduce

- Open any file after a user with a different file system time lints it and it syncs to the vault.
- Run Linter.
- The modified date will change.
Config

## Config
```

{
  "ruleConfigs": {
    "add-blank-line-after-yaml": {
      "enabled": false
    },
    "dedupe-yaml-array-values": {
      "enabled": false,
      "dedupe-alias-key": true,
      "dedupe-tag-key": true,
      "dedupe-array-keys": true,
      "ignore-keys": ""
    },
    "escape-yaml-special-characters": {
      "enabled": false,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": false,
      "force-yaml-escape-keys": ""
    },
    "format-tags-in-yaml": {
      "enabled": false
    },
    "format-yaml-array": {
      "enabled": false,
      "alias-key": true,
      "tag-key": true,
      "default-array-style": "single-line",
      "default-array-keys": true,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": ""
    },
    "insert-yaml-attributes": {
      "enabled": false,
      "text-to-insert": "aliases: \ntags: "
    },
    "move-tags-to-yaml": {
      "enabled": false,
      "how-to-handle-existing-tags": "Nothing",
      "tags-to-ignore": ""
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "sort-yaml-array-values": {
      "enabled": false,
      "sort-alias-key": true,
      "sort-tag-key": true,
      "sort-array-keys": true,
      "ignore-keys": "",
      "sort-order": "Ascending Alphabetical"
    },
    "yaml-key-sort": {
      "enabled": false,
      "yaml-key-priority-sort-order": "",
      "priority-keys-at-start-of-yaml": true,
      "yaml-sort-order-for-other-keys": "None"
    },
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "Date Created",
      "date-created-source-of-truth": "file system",
      "date-modified": true,
      "date-modified-key": "Last Modified",
      "date-modified-source-of-truth": "file system",
      "format": "lll",
      "convert-to-utc": false,
      "update-on-file-contents-updated": "never"
    },
    "yaml-title": {
      "enabled": false,
      "title-key": "title",
      "mode": "first-h1-or-filename-if-h1-missing"
    },
    "yaml-title-alias": {
      "enabled": false,
      "preserve-existing-alias-section-style": true,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
      "alias-helper-key": "linter-yaml-title-alias"
    },
    "capitalize-headings": {
      "enabled": false,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript, I",
      "lowercase-words": "a, an, the, aboard, about, abt., above, abreast, absent, across, after, against, along, aloft, alongside, amid, amidst, mid, midst, among, amongst, anti, apropos, around, round, as, aslant, astride, at, atop, ontop, bar, barring, before, B4, behind, below, beneath, neath, beside, besides, between, 'tween, beyond, but, by, chez, circa, c., ca., come, concerning, contra, counting, cum, despite, spite, down, during, effective, ere, except, excepting, excluding, failing, following, for, from, in, including, inside, into, less, like, minus, modulo, mod, near, nearer, nearest, next, notwithstanding, of, o', off, offshore, on, onto, opposite, out, outside, over, o'er, pace, past, pending, per, plus, post, pre, pro, qua, re, regarding, respecting, sans, save, saving, short, since, sub, than, through, thru, throughout, thruout, till, times, to, t', touching, toward, towards, under, underneath, unlike, until, unto, up, upon, versus, vs., v., via, vice, vis-à-vis, wanting, with, w/, w., c̄, within, w/i, without, 'thout, w/o, abroad, adrift, aft, afterward, afterwards, ahead, apart, ashore, aside, away, back, backward, backwards, beforehand, downhill, downstage, downstairs, downstream, downward, downwards, downwind, east, eastward, eastwards, forth, forward, forwards, heavenward, heavenwards, hence, henceforth, here, hereby, herein, hereof, hereto, herewith, home, homeward, homewards, indoors, inward, inwards, leftward, leftwards, north, northeast, northward, northwards, northwest, now, onward, onwards, outdoors, outward, outwards, overboard, overhead, overland, overseas, rightward, rightwards, seaward, seawards, skywards, skyward, south, southeast, southwards, southward, southwest, then, thence, thenceforth, there, thereby, therein, thereof, thereto, therewith, together, underfoot, underground, uphill, upstage, upstairs, upstream, upward, upwards, upwind, west, westward, westwards, when, whence, where, whereby, wherein, whereto, wherewith, although, because, considering, given, granted, if, lest, once, provided, providing, seeing, so, supposing, though, unless, whenever, whereas, wherever, while, whilst, ago, according to, as regards, counter to, instead of, owing to, pertaining to, at the behest of, at the expense of, at the hands of, at risk of, at the risk of, at variance with, by dint of, by means of, by virtue of, by way of, for the sake of, for sake of, for lack of, for want of, from want of, in accordance with, in addition to, in case of, in charge of, in compliance with, in conformity with, in contact with, in exchange for, in favor of, in front of, in lieu of, in light of, in the light of, in line with, in place of, in point of, in quest of, in relation to, in regard to, with regard to, in respect to, with respect to, in return for, in search of, in step with, in touch with, in terms of, in the name of, in view of, on account of, on behalf of, on grounds of, on the grounds of, on the part of, on top of, with a view to, with the exception of, à la, a la, as soon as, as well as, close to, due to, far from, in case, other than, prior to, pursuant to, regardless of, subsequent to, as long as, as much as, as far as, by the time, in as much as, inasmuch, in order to, in order that, even, provide that, if only, whether, whose, whoever, why, how, or not, whatever, what, both, and, or, not only, but also, either, neither, nor, just, rather, no sooner, such, that, yet, is, it"
    },
    "file-name-heading": {
      "enabled": false
    },
    "header-increment": {
      "enabled": false,
      "start-at-h2": false
    },
    "headings-start-line": {
      "enabled": false
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": false,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "footnote-after-punctuation": {
      "enabled": false
    },
    "move-footnotes-to-the-bottom": {
      "enabled": false
    },
    "re-index-footnotes": {
      "enabled": false
    },
    "auto-correct-common-misspellings": {
      "enabled": false,
      "ignore-words": "",
      "skip-words-with-multiple-capitals": false,
      "extra-auto-correct-files": []
    },
    "blockquote-style": {
      "enabled": false,
      "style": "space"
    },
    "convert-bullet-list-markers": {
      "enabled": false
    },
    "default-language-for-code-fences": {
      "enabled": false,
      "default-language": ""
    },
    "emphasis-style": {
      "enabled": false,
      "style": "consistent"
    },
    "no-bare-urls": {
      "enabled": false,
      "no-bare-uris": false
    },
    "ordered-list-style": {
      "enabled": false,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": false
    },
    "quote-style": {
      "enabled": false,
      "single-quote-enabled": true,
      "single-quote-style": "''",
      "double-quote-enabled": true,
      "double-quote-style": "\"\""
    },
    "remove-consecutive-list-markers": {
      "enabled": false
    },
    "remove-empty-list-markers": {
      "enabled": false
    },
    "remove-hyphenated-line-breaks": {
      "enabled": false
    },
    "remove-multiple-spaces": {
      "enabled": false
    },
    "strong-style": {
      "enabled": false,
      "style": "consistent"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": false,
      "line-break-indicator": "  "
    },
    "unordered-list-style": {
      "enabled": false,
      "list-style": "consistent"
    },
    "compact-yaml": {
      "enabled": false,
      "inner-new-lines": false
    },
    "consecutive-blank-lines": {
      "enabled": false
    },
    "convert-spaces-to-tabs": {
      "enabled": false,
      "tabsize": 4
    },
    "empty-line-around-blockquotes": {
      "enabled": false
    },
    "empty-line-around-code-fences": {
      "enabled": false
    },
    "empty-line-around-horizontal-rules": {
      "enabled": false
    },
    "empty-line-around-math-blocks": {
      "enabled": false
    },
    "empty-line-around-tables": {
      "enabled": false
    },
    "heading-blank-lines": {
      "enabled": false,
      "bottom": true,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": false
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": false
    },
    "paragraph-blank-lines": {
      "enabled": false
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": false
    },
    "remove-link-spacing": {
      "enabled": false
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": true,
      "other-symbols": ""
    },
    "remove-space-before-or-after-characters": {
      "enabled": false,
      "characters-to-remove-space-before": ",!?;:).’”]",
      "characters-to-remove-space-after": "¿¡‘“(["
    },
    "space-after-list-markers": {
      "enabled": false
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false,
      "english-symbols-punctuation-before": "-+;:'\"°%$)]",
      "english-symbols-punctuation-after": "-+'\"([¥$"
    },
    "trailing-spaces": {
      "enabled": false,
      "two-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": false
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": false
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": false
    },
    "proper-ellipsis-on-paste": {
      "enabled": false
    },
    "remove-hyphens-on-paste": {
      "enabled": false
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": false
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": false
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": false
    }
  },
  "lintOnSave": true,
  "recordLintOnSaveLogs": true,
  "displayChanged": true,
  "lintOnFileChange": true,
  "displayLintOnFileChangeNotice": true,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [
    "Templates"
  ],
  "filesToIgnore": [],
  "linterLocale": "en-us",
  "logLevel": "DEBUG",
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single-line",
    "tagArrayStyle": "single-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\"",
    "removeUnnecessaryEscapeCharsForMultiLineArrays": false
  }
}
```
## Logs

```
Running linter
rules before regular rules: 0.09999990463256836 ms
Running Custom Regex
custom regex rules: 0.09999990463256836 ms
Running YAML Timestamp
yaml-timestamp: 0.5999999046325684 ms
---
Date Created: Oct 7, 2025 8:33 AM
Last Modified: Oct 15, 2025 1:45 AM
Connected Files:
  - - Select Note
sticker: vault//Trolic
---

- [x] [[CC Task 1 Queue & Server Reservations]]
	- [x] [[CC Tune Ups]]
- [x] [[CC Task 2 Game Sequence (GS)]]
	- [x] [[CC Tune Ups]]
- [x] [[CC Task 3 Settings]]
- [x] [[GS Task 3]]
	- [x] Currently [[GS Task 3#Current Issues]]
- [x] :MiBluemond: For Theme Pools, I meant for the theme definition to remain decoupled from the theme pools definition, where just the names of the themes would be listed in a theme pool's definition
	![[Pasted image 20251001223142.png]]
	You moved the definition of the themes within the theme pools definition, but it should look more like this (while retaining the original themes files and using it to grab the data for the themes defined in the theme pools)
	```lua
	ThemePools.WeightTable = {
	    {
	        Weight = 50,
	        Themes = {
		        "Magic",
		        "Avatar",
		        "Etc.."
			}
		}
	}
	```
	This will allow easier movement and adjustment of the Theme Pools
- [x] [[Catalog Tune Up]]
- [x] [[UIStroke Scaling]]
rules after regular rules: 0.9000000953674316 ms
rules running: 1.0999999046325684 ms
```

## Expected Behavior

Linter do not changed the modified date if no modifications are made.

## Screenshots

<img width="1071" height="370" alt="Image" src="https://github.com/user-attachments/assets/750a842b-0977-43bc-b614-55f32a5fab73" />
<img width="1627" height="412" alt="Image" src="https://github.com/user-attachments/assets/984ceb7b-cfcb-4b2c-a713-e0beaf48359c" />
<img width="1650" height="447" alt="Image" src="https://github.com/user-attachments/assets/00cdfa34-e4e4-4b65-8f6a-36f43ebb6b59" />

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@Bluemandan,  thanks for mentioning this. Could you explain why you are using file system metadata as the source of truth and syncing between devices? That setup says that whatever the filesystem says is the date modified is the one to use. Syncing a change will cause that files date modified to be updated on your system from my understanding. So no change may have been made, but if the timestamp of when it was last modified according to the file system is more than 5 seconds from when it says in the front after, it will force an update.

**Comment by pjkaufman** [comment]
Another issue I am noticing is that you are not using UTC/including timezone information. So unless the other user is in the same timezone, this will force the timestamp to be updated since no timezone defaults to the current timezone as the assumed one.

**Comment by pjkaufman** [comment]
I would recommend using UTC time in your date modified if you plan on using filesystem and different timezones. That will not guarantee that the timestamp does not get updated since you have a 5 second window for the file to get synced to you after it is linted. But it should at least mitigate some scenarios.

**Comment by Bluemandan** [comment]
Will I have the source of truth set to file system because that is the only way to lint a file if "Lint on Focused File Change" is the only method enabled. If sourced of truth is set to "Changes in Obsidian", it will not lint. Unless I enabled a lint timer or manual lint, but this is why I advocate for changes in Obsidian to be checked when Focused File Changes. The reason I don't use UTC is because everyone who uses the vault lives in the east coast of the US except for the 1 person, personally Its annoying and as you said it wouldn't solve this issue. Also does Override Locale not override information coming from the file system?

Also with source of truth set to file system, why would it only update the date modified and not the creation date?

Thanks!

**Comment by pjkaufman** [comment]
I will try my best to answer questions posed here and explain how things work, but `yaml-timestamp` is getting to be one of those rules that it seems has a lot of disconnect between how things work on the backend versus how the user expects them to work. Granted, some of the confusion is because I am a backend dev and probably don't document/communicate how they work well enough. That said, I will move on to what you have stated and said.

> Will I have the source of truth set to file system because that is the only way to lint a file if "Lint on Focused File Change" is the only method enabled. If sourced of truth is set to "Changes in Obsidian", it will not lint. Unless I enabled a lint timer or manual lint, but this is why I advocate for changes in Obsidian to be checked when Focused File Changes.

File system as the source of truth works very badly for synced systems since what matters is what the filesystem says about the time it was modified (I will take a look at the created value later since I am less familiar with that right now). The whole point of the option for user or Linter edits is meant for a synced system or one where you don't care what the file system says, but rather when the file was last changed. But it comes with the drawback of only being able to be accurate when using the update timestamp after x seconds option since the Linter can no longer know when you make changes to a file since the file system cannot be used to know if a change was made and the Linter has no knowledge during lint about any changes that the Linter has not made itself. It is not keeping track of user changes in the file. So that is why it does not update the timestamp if you manually update a file and then change while file is focused if the Linter has no formatting changes it makes.

As for `but this is why I advocate for changes in Obsidian to be checked when Focused File Changes.`  The only reference to a change I see in this issue is

> Linter do not changed the modified date if no modifications are made.

My interpretation of this statement is as follows and may be wrong, so feel free to correct me if I am wrong:
The Linter should know when a user edits a file even outside of when the Linter is asked to run. It should then know that when it next tries to the lint the file while Obsidian is running (if it closes between the change and the next lint it will not know) then it will force a timestamp update even if the Linter would not have otherwise updated the timestamp. Timestamp format changes and other reasons to update the timestamp should be ignored under this option.

I don't personally have a desire to implement something like that since it balloons how the Linter works and adds more things to maintain. But if someone knows a simple and maintainable approach to the above that is backwards compatible, I would be fine with having it added to the codebase. If my interpretation of what is being asked is wrong, please let me know.

> The reason I don't use UTC is because everyone who uses the vault lives in the east coast of the US except for the 1 person, personally Its annoying and as you said it wouldn't solve this issue.

I can't say that it will not fix this issue. However, changing to UTC should at least fix the issue that it is currently facing where the file system and the file will always be at odds with each other so long as the timestamp is not for the timezone of the file system.

Now, I don't know how you are syncing the notes across machines. If you are sharing a single vault and making the changes on a machine you have remoted into, then the UTC change may be needles. However if you are using something where the files are copied to each file system and not on one file system then this should at least help some. It will not help in the situation where the sync takes longer than 5 seconds to get the file from one person's system to another.

> Also does Override Locale not override information coming from the file system?

I am not sure I fully understand where the question is coming from. Maybe it comes across as specifying where a timezone comes from, but a locale is typically a language from my understanding. So setting locale just specifies that the output format should be in x language (US English, Chinese, French, Spanish, etc.). So having the same locale just means that it will use the same language. The system locale is the locale you specified in Obsidian for your language. There may be a better way to refer to that in the UI, but that is how that works. The moment docs [https://momentjs.com/docs/](https://momentjs.com/docs/) seem to have no reference to locale other than for language purposes if I am seeing correctly. Hopefully that clears up why locale is not really related to the file system.

> Also with source of truth set to file system, why would it only update the date modified and not the creation date?

This is definitely an interesting question to me. I agree it seems off. For date modified, any of the following cause an update to the date modified:
- A change was made by the Linter
- The format in the settings and the format of the date in the frontmatter do not match
- The locale in the settings and the locale of the date in the frontmatter do not match
- Moment either fails to parse the date from the frontmatter or says it is invalid
- The source of truth is the file system and the difference in time between the file metadata and the value in the frontmatter differ more than 5 seconds
  - Gives a 5 second buffer since the file system and the file display value will almost never be equal due to the time it takes to write to the file system after a file saves

Here is when the date created is updated based on the code when a value already exists in the frontmatter:
- The format in the settings and the format of the date in the frontmatter do not match
- The locale in the settings and the locale of the date in the frontmatter do not match
- If the system is the source of truth
  - Moment either fails to parse the date from the frontmatter or says it is invalid

So, the reason it is not affecting created date is the inconsistent way it handles file creation checks which is either due to a separate bug fix or something I missed when I initially added `frontmatter` vs `file system` dates.

This would mean changing the date created date to get updated under the following circumstances (change is in bold):
- The format in the settings and the format of the date in the frontmatter do not match
- The locale in the settings and the locale of the date in the frontmatter do not match
- If the system is the source of truth
  - Moment either fails to parse the date from the frontmatter or says it is invalid
    - This cannot be done when the `frontmatter` is the source of truth since there is a non-empty key, so the user has to fix it themselves
  - **Check to make sure that the date created is the exact same between the two dates**

Hopefully that makes things a little clearer. There is a change that looks like it needs to happen to the date created logic, but the other logic seems correct to me

**Comment by Bluemandan** [comment]
omg, thank you a lot for the detailed reply — really appreciate you taking the time to break everything down! That clears up a lot of the confusion I had around how lint on focus interacts with the timestamp rule and the specific conditions where Obsidian actually commits the update. As well I understand not wanting to bloat up the plugin. Also mb, I read somewhere that Override Locale also was related to time zone, but that wouldn't make much sense when looking at the options lol. Your explanation about when lint runs and how the file update logic works makes sense now. Thanks again for going into that level of detail!

**Comment by pjkaufman** [comment]
No problem. I am glad it cleared up some things. Hopefully this allows for a path forward to resolving your issue.

If my understanding is correct the following is all that is left for this issue:
- Look into why date created is not updated when the date created value for the file differs and file system is the source of truth (is it a bug or is there an actual reason for it that needs documenting)
- Possibly add some more docs around when `yaml-timestamp` modification are made
- Fix date created not being updated if it is a bug

**Comment by droped** [comment]
@pjkaufman 

> I don't personally have a desire to implement something like that since it balloons how the Linter works and adds more things to maintain. But if someone knows a simple and maintainable approach to the above that is backwards compatible, I would be fine with having it added to the codebase. If my interpretation of what is being asked is wrong, please let me know.

What about storing a CRC32 (it's fast and ubiquitous) hash for the file in a database? When the linter is first run, a CRC32 hash is generated for the full path of the file and stored in a database (like a json file), if the linter is run again and the hash is different then change the last modified value to the current date. No need for background services, and a simple cache file containing the full path and hash in a key value pair should be simple to implement. It also doesn't need any setup since it only stores the files you manually force linter to run on. This would also prevent any system attribute changes from messing with the file, since they are independent of the file itself. There's also little need to prune the cache file, since unless you have hundreds of thousands of files, a simple key value pair should be fast enough to retrieve and change.

**Comment by pjkaufman** [comment]
> [@pjkaufman](https://github.com/pjkaufman)
> 
> > I don't personally have a desire to implement something like that since it balloons how the Linter works and adds more things to maintain. But if someone knows a simple and maintainable approach to the above that is backwards compatible, I would be fine with having it added to the codebase. If my interpretation of what is being asked is wrong, please let me know.
> 
> What about storing a CRC32 (it's fast and ubiquitous) hash for the file in a database? When the linter is first run, a CRC32 hash is generated for the full path of the file and stored in a database (like a json file), if the linter is run again and the hash is different then change the last modified value to the current date. No need for background services, and a simple cache file containing the full path and hash in a key value pair should be simple to implement. It also doesn't need any setup since it only stores the files you manually force linter to run on. This would also prevent any system attribute changes from messing with the file, since they are independent of the file itself. There's also little need to prune the cache file, since unless you have hundreds of thousands of files, a simple key value pair should be fast enough to retrieve and change.

I can't say I am completely against the idea as I have toyed with the idea of using a way to keep track of what changes. However that file would not be synced across devices based on how things work in Obsidian Sync (mileage may vary for other sources). Beyond that, it would have to keep track of renames and changes like that. So it would take a decent bit of work yet.

But if I am being honest, it has been so long that I would need to know what specific use case this would help out with for users. It seems for the most part that making created and modified date consistent in how they operate and then letting the user specify whether the file metadata is the source of truth or changes made in Obsidian. Could you elaborate on which scenario you are thinking the hash would help with?

**Comment by droped** [comment]
Since Linter only recognises its own changes in "Changes in Obsidian", I enabled "Update YAML Timestamp on File Contents Update" to keep it properly updated. But that setting adds the updated time to all files that I interact with, so I had to disable it because it kept messing with my files. 

The problem with "File system" as the source of truth is that I keep a backup among 3 locations (with different underlying file systems and used by different operating systems) that I constantly use. This means that any synced file will automatically have its modified time changed when it is synced, but it also means all three locations have entirely different modified times (they also have different creation times, but I fixed that by simply setting the creation time at file creation using the templater plugin and never updating it). Since I sync the .obsidian folder, the cache would be synced too and there would be no problem (at least for me).

This change would fix all these issues, keeping it properly updated, preventing Linter from adding the modified date into random files without me explicitly invoking it and not relying on the unreliable file system modified time.

**Comment by droped** [comment]
File name changes don't affect the modified timestamp on Windows (and other file systems, I assume) so they are irrelevant.

If you mean changing the name or moving the file inside the vault while keeping the content intact, Linter could just update the new location in the database if it finds the same hash for another file (this would also help in keeping the database small). As for duplicate files, this is irrelevant. As soon the date changes on one file, they stop being duplicates anyway and would be attributed to a new key value pair on the database.

Collisions are unlikely because in most scenarios, a new character on a text file cascades the hash, and irrelevant as well since this is not meant for cryptographic purposes (crc is not cryptographic anyway).

**Comment by pjkaufman** [comment]
@droped , sorry it has been a while. Could you explain how the hash would solve the problem if update YAML timestamp after x seconds did not fix the issue? The update YAML timestamp after x seconds is only triggered when Obsidian says a file is changed (if I recall it is only when a file is changed in the editor). So I am not sure how you would be getting date modified values in files you did not actually make any changes to at all.

**Comment by droped** [comment]
The newer linter version updates the modified time all the time, so idk.

**Comment by pjkaufman** [comment]
Could you elaborate on what you mean by the Linter updates the modified time all the time?

If the source of truth is set to changes in Obsidian and you use the update timestamp setting after every x seconds, it should only update a file x seconds after it registers the last change. So I am not sure I follow whether from what you are saying it is working the way I have described here or if something else is going on. And I am not sure what your intended scenario is for when the date modified should be updated (only when you make a change in Obsidian or run the Linter and it makes a change or technically anything that updates a file in Obsidian itself or just when you manually trigger it).

I am guessing this is just me not understanding what the desired functionality is versus the gap in what currently exists.
